[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32G474CETx --connect-under-reset'

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["core", "panic_abort"]
# Uncomment to get rid of all the panic messages, makes it a lot harder to debug but saves a lot of space
build-std-features = ["panic_immediate_abort"]