[target.thumbv7em-none-eabihf]
# runner = 'rocket-cli download STM32G474CETx ../../Rust_Monorepo/bootloader/secret.key ozys'
runner = 'probe-rs run --chip STM32G474CETx --connect-under-reset'

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug,embassy_stm32=info"

[unstable]
build-std = ["core"]
# Uncomment to get rid of all the panic messages, makes it a lot harder to debug but saves a lot of space
# build-std-features = ["panic_immediate_abort"]